nombre = input("Cual es tu nombre? ")
apellido = input("Cual es tu apellido? ")
asignatura = input("Cual es tu asignatura? ")
sede = input("Cual es tu sede? ")
semestre = input("Cual es tu semestre? ")
año = input("Cual es tu año? ")
print("hola",nombre,apellido,"de la asignatura",asignatura,"de la sede",sede,"del semestre",semestre,"del año",año)
